Task 12 is done
belyalex/made_2019_algo pull request #10
Opened 2019-12-07 17:38 UTC by belyalex

https://contest.yandex.ru/contest/15957/run-report/28159882/

2019-12-13 02:05 UTC, smatskevich requested changes
Прошу прощения, что только сейчас говорю.
Вы в субботу спрашивали про рекурсию. Мы обсудили с семинаристами - нельзя ее в этой задаче использовать. Одна из причин - рекурсивный код есть в лекции ))
Исправьте, пожалуйста.

2019-12-17 09:58 UTC, belyalex commented
Переделал на нерекурсивный обход.
https://contest.yandex.ru/contest/16167/run-report/29009723/

2019-12-28 17:35 UTC, smatskevich approved these changes
Принято.

2019-12-28 17:35 UTC, smatskevich commented on 12/main.cpp
> +    for (auto b:bridges) {
Пробелов вокруг : не хватает )

2019-12-28 17:35 UTC, smatskevich commented on 12/main.cpp
> +    std::vector<std::vector<size_t>> vertexes; //для каждой вершины храним вектор смежных вершин
Вместо параллельных векторов предпочитаю вектор структур.

2019-12-28 17:35 UTC, smatskevich commented on 12/main.cpp
> +                goto next;
Ого. Хитро :)

2019-12-28 17:35 UTC, smatskevich commented on 12/main.cpp
> +    std::stack<std::tuple<size_t, size_t, size_t>> stack; // в стеке храним вершину, номер смежной вершины и номер ребра
Похоже третьим параметром хранится не номер ребра, а родительская вершина.

2019-12-28 17:35 UTC, smatskevich commented on 12/main.cpp
> +                std::get<1>(stack.top())=i;
Такие штуки стоит комментировать.

2019-12-28 17:45 UTC, belyalex commented on 12/main.cpp
> +    std::stack<std::tuple<size_t, size_t, size_t>> stack; // в стеке храним вершину, номер смежной вершины и номер ребра
Именно номер ребра. В случае кратных рёбер, я проверяю, что не пытаюсь вернуться по тому же ребру в родительскую вершину.

2019-12-28 17:47 UTC, belyalex commented on 12/main.cpp
> +                std::get<1>(stack.top())=i;
Тут на вершине стека перезаписываем номер последней рассмотренной смежной вершины.

2019-12-28 17:53 UTC, belyalex commented on 12/main.cpp
> +                goto next;
Я знал, что Вам понравится :)

2019-12-28 17:53 UTC, merged

2019-12-28 22:48 UTC, smatskevich commented on 12/main.cpp
> +    std::stack<std::tuple<size_t, size_t, size_t>> stack; // в стеке храним вершину, номер смежной вершины и номер ребра
Ok