16 задача
belyalex/made_2019_algo pull request #13
Opened 2019-12-19 18:30 UTC by belyalex

https://contest.yandex.ru/contest/16186/run-report/29097240/

2019-12-30 10:22 UTC, smatskevich requested changes
Нужно решение, в котором доп память выделяется только для z-функции шаблона.
Не надо конкатенировать строки.
Значения z-функции никогда не будут больше `|p|`, поэтому можно представить, что вы идете как будто по конкатенированной строке, вычисляете z-функцию. Но используете ее значения только для малых индексов меньших `|p|`. Это позволяет ее не хранить для больших значений индексов.

2019-12-30 10:22 UTC, smatskevich commented on 16/main.cpp
> +    s=t+"#"+s;
Это O(t+s) по памяти.

2020-01-03 11:02 UTC, belyalex commented on 16/main.cpp
> +    s=t+"#"+s;
Поправил

2020-01-03 19:49 UTC, smatskevich approved these changes
Тесты пройдены. Принято.

2020-01-03 19:51 UTC, merged