Task 8 is done
belyalex/made_2019_algo pull request #7
Opened 2019-11-22 12:05 UTC by belyalex

https://contest.yandex.ru/contest/15369/run-report/26719190/

2019-12-01 00:13 UTC, smatskevich requested changes
Поправьте, пожалуйста, хранение table.

2019-12-01 00:13 UTC, smatskevich commented on 08/main.cpp
> +    PHashTableNode* table = nullptr; //собственно хэштаблица - динамический массив указателей на HashTableNode
Можно и лучше использовать вектор.
Не надо хранить массив указателей - так много аллокаций. Лучше vector<HashTableNode> - память существенно сэкономите и не будет фрагментации.
Поправьте, пожалуйста, и код упроститься.

2019-12-01 00:13 UTC, smatskevich commented on 08/main.cpp
> +            if ((p->hash == hash) && (p->value == s)) {
Да, оптимизация может помочь, если строки с общим префиксом и сильная заполненность таблицы. Но это маловероятно, а на hash тратится память и сравнения.

2019-12-01 00:13 UTC, smatskevich commented on 08/main.cpp
> +    if (size * 4 == capacity * 3) {
Лучше сравнивать >=, чтобы не переживать )

2019-12-01 00:13 UTC, smatskevich commented on 08/main.cpp
> +        PHashTableNode *oldTable = table;
Перехеширование лучше выделить в отдельный метод.

2019-12-02 14:27 UTC, belyalex commented
Поправил замечания

2019-12-09 23:30 UTC, smatskevich approved these changes
Тесты пройдены.
Принято.

2019-12-09 23:37 UTC, merged